# This file is part of censusgeocode.
# https://github.com/fitnr/censusgeocode

# Licensed under the General Public License (version 3)
# http://opensource.org/licenses/LGPL-3.0
# Copyright (c) 2015-7, Neil Freeman <contact@fakeisthenewreal.org>

language: python

python:
    - 3.6
    - 3.7
    - 3.8
    - 3.9

matrix:
    fast_finish: true

before_install:
    - pip install coverage vcrpy

install:
    - python setup.py install

script:
    - coverage run --source=censusgeocode -m unittest test
    - censusgeocode --version
    - censusgeocode --csv tests/fixtures/batch.csv || echo failed

after_success:
    - coverage report
